### ISSUE TITLE
/es/about 404

### ISSUE THREAD

**Issue by wanghaisheng** [jlarmstrongiv/astro-i18n-aut#10]
follow doc configure

**Comment by wanghaisheng** [comment]
github.com/wanghaisheng/idea-to-action-cycle

**Comment by jlarmstrongiv** [comment]
You need to be consistent with either:
- `config.trailingSlash = "always" && config.build.format = "directory"`
- `config.trailingSlash = "never" && config.build.format = "file"`

If you set trailing slash to always, then `/es/about` will 404 because you need `/es/about/` and vice versa

**Comment by jlarmstrongiv** [comment]
@wanghaisheng I have updated the README to reflect proper use of slashes.  My apologies for the confusion.
