### ISSUE TITLE
Not respecting Astro's excluding routing rule

### ISSUE THREAD

**Issue by MarvinXu** [jlarmstrongiv/astro-i18n-aut#29]
[Routing 🚀 Astro Documentation](https://docs.astro.build/en/core-concepts/routing/#excluding-pages)
> You can exclude pages or directories from being built by prefixing their names with an underscore (_). Files with the _ prefix won’t be recognized by the router and won’t be placed into the dist/ directory.

Actual builds:
├── cn
│   ├── _about
│   │   └── index.html
│   ├── _blog
│   │   └── index.html
│   └── index.html
├── en
│   ├── _about
│   │   └── index.html
│   ├── _blog
│   │   └── index.html
│   └── index.html

**Comment by jlarmstrongiv** [comment]
Follow https://github.com/jlarmstrongiv/astro-i18n-aut/pull/30 for updates
