### ISSUE TITLE
redirectDefaultLocale behaviour

### ISSUE THREAD

**Issue by dallyh** [jlarmstrongiv/astro-i18n-aut#37]
Hello,

this is more of a question than issue.

I'm struggling a little bit with the `redirectDefaultLocale` option. I want my site to have paths for every language possible, that is for example "en, cs, fr" -> /en/page/, /cs/page/, /fr/page/.

When i set the `redirectDefaultLocale ` to false, and my `defaultLocale` is "en", then /en/page/ returns 404. When the redirectDefaultLocale is in it's default state, then /en/page/ redirects to /page/. When I manually create /en/page/, then every other language is not automatically generated (404's).

Is it possible to make it so this integration generates paths for every language, even if it's the default one?

Thanks!

**Comment by jlarmstrongiv** [comment]
Hi @dallyh, 

This library is mostly meant to support the use-case of having a `defaultLocale` with Astro, without having to duplicate `/about.astro` and `/es/about.astro`

If you don’t want a `defaultLocale`, then you can use this [Astro cookbook recipe](https://docs.astro.build/en/recipes/i18n/) or their upcoming their [experimental router](https://docs.astro.build/en/guides/internationalization/#i18n-routing-experimental).  Or, you can just use `src/pages/[lang]/about.astro`.  I think those options are better for your use case, and do not plan to support it in this library.  I hope these links point you in the right direction though

This library solves a problem that neither their cookbook nor experimental router solves:  having a `defaultLocale` without page duplication

---

The `redirectDefaultLocale` controls the behavior of `/en/about`, when `en` is the `defaultLocale`.  Setting `redirectDefaultLocale` means `/en/about` will redirect to `/about`, while setting it to false means `/en/about` will return a 404

**Comment by dallyh** [comment]
@jlarmstrongiv 

Thanks for the response, and I got it thanks. 

But this integration solves more than the `defaultLocale` and that is, it solves the manual work required (set up every page individually) to use either the cookbook recipe or experimental router. Of course I could set up a script that does this for me, but this integration does everything conveniently in the background with minimal configuration.

**Comment by dallyh** [comment]
@jlarmstrongiv Thanks for your help and explanation, I appreciate it. I don't feel like a developer that could handle such task of refactoring the whole library.

The combination of dynamic [lang] path and Astro's new i18n router works well, but there are some quirks as of now. 

Again thanks for all the information :)

**Comment by jlarmstrongiv** [comment]
@dallyh it’s certainly possible—I rewrote the library once to support the [`base`](https://docs.astro.build/en/reference/configuration-reference/#base) option.  But, it’s definitely a lot faster to use the dynamic `[lang]` path.  Anyway, glad the suggestions helped 😄
