### ISSUE TITLE
The translation pages take a very long time to build

### ISSUE THREAD

**Issue by tiwka19** [jlarmstrongiv/astro-i18n-aut#39]
On dynamic pages ( such as blog ) I send graphql query to get data in different languages. It looks something like this

```
export async function getStaticPaths({ paginate }) {
  const directus = await getDirectusClient();
  const data = await directus.query(`
    query {  
      posts (
        filter: { 
          translations: {content: {_null: false}} 
          status: {_eq: "published"}} 
          sort: ["-date_created"]
        ){ 
        slug 
      } 
    }
  `);
  return paginate(data.posts, { pageSize: 12 });
}
```
And this is how long it takes to build. Why does the default language take several times less time to build than ru?

13:09:51 ▶ src/astro_tmp_pages_en/blog/[slug].astro
13:09:52   └─ /en/blog/how-to-use-cookies-bot.html (+4ms)
13:09:52 ▶ src/astro_tmp_pages_ru/blog/[slug].astro
13:09:56   └─ /ru/blog/how-to-use-cookies-bot.html (+2.55s)

**Comment by jlarmstrongiv** [comment]
Please only keep pages in your `pages` folder.  If you add images, components, test files, etc. in the `pages` folder, then the build will be very slow.

For translations, `astro-i18n-aut` has to write files to disk due to an Astro core bug where `injectRoute` cannot be used with the same `entryPoint` Astro files.  Unfortunately, any operation that has to write to the file system will always be slower.

**Comment by tiwka19** [comment]
> Please only keep pages in your `pages` folder. If you add images, components, test files, etc. in the `pages` folder, then the build will be very slow.
> 
> For translations, `astro-i18n-aut` has to write files to disk due to an Astro core bug where `injectRoute` cannot be used with the same `entryPoint` Astro files. Unfortunately, any operation that has to write to the file system will always be slower.

I only keep pages in the pages folder. It's just very strange that I request both en language and ru language from the server, but there is such a huge time difference

**Comment by jlarmstrongiv** [comment]
@tiwka19 it is strange that it would be slower after being deployed.  It should only be slower during build

Would you send me a live website link and which platform you are deploying on?  Do you have a public GitHub repo by chance?

**Comment by tiwka19** [comment]
> @tiwka19 it is strange that it would be slower after being deployed.  It should only be slower during build
> 
> Would you send me two live website links to compare and which platform you are deploying on?  Do you have a public GitHub repo by chance?

I take the data from directus. My entire site is SSG. It's about the build time. I just don't understand why there is such a time difference if both languages are taken by API. 
Unfortunately, I cannot provide the source code. I can show code snippets of dynamic pages

**Comment by tiwka19** [comment]
> @tiwka19 it is strange that it would be slower after being deployed. It should only be slower during build
> 
> Would you send me two live website links to compare and which platform you are deploying on? Do you have a public GitHub repo by chance?

Duration~8 mins. 54 secs. That's how long it takes to build a website. And that's only in two languages. And in the future I will have about 6.   0_0

**Comment by tiwka19** [comment]
![en](https://github.com/jlarmstrongiv/astro-i18n-aut/assets/61656257/e3069beb-4c48-4e4a-8749-da2f5a4f2a8f)
![ru](https://github.com/jlarmstrongiv/astro-i18n-aut/assets/61656257/9ed214d7-80e0-40d5-baf9-8e1950d121b0)
 look at the difference

**Comment by jlarmstrongiv** [comment]
After chatting with @natemoo-re, we believe it’s a core Astro issue with `injectRoute`.  I’m not sure where to go from here, so feel free to open an issue in Astro core

**Comment by tiwka19** [comment]
> After chatting with @natemoo-re, we believe it’s a core Astro issue with `injectRoute`.  I’m not sure where to go from here, so feel free to open an issue in Astro core

So problem persists if use official i18 integration from astro?

**Comment by jlarmstrongiv** [comment]
@tiwka19 unfortunately, I do not know how the official integration works

**Comment by jlarmstrongiv** [comment]
@tiwka19 did you create an issue in the Astro core repository?
