### ISSUE TITLE
Build failed on Windows

### ISSUE THREAD

**Issue by hoqn** [jlarmstrongiv/astro-i18n-aut#4]
Hi there!
I really like this work, but I've got small problem:

Build failed on Windows with the following error message:
`Error: ENOENT: no such file or directory, lstat 'C:\C:\Users\hoqn\...\src\pages'`

**Comment by hoqn** [comment]
After some debugging to resolve this error, I discovered that the config's paths from astro's Integration API all contain a leading slash. This causes an error on Windows.

So, I thought astro's api has a bug.... But I found this:
https://github.com/withastro/astro/blob/864291212036819df9c3e5ad2dee5d921c1bdec8/packages/internal-helpers/src/path.ts#L26

They were aware of these issues, and they use an internal util function. So, I think I can fix this issue with some addition.

Is it ok to PR later?

**Comment by jlarmstrongiv** [comment]
Thank you for investigating @hoqn !  I don’t have a windows machine, so that would’ve been hard to track down.  PRs welcome!

**Comment by jlarmstrongiv** [comment]
Hi @hoqn 👋

I tried reproducing the bug on a windows machine, but it seemed to work fine.  Looking at `path.join(config.srcDir.pathname, "pages")`, it seems:
- the default value of `./src` is fine
- absolute path of `C:\\Users\\username\\source\\repos\\TryAstroBug\\cyan-conjunction\\src` fails
- absolute path of `/Users/username/source/repos/TryAstroBug/cyan-conjunction/src` works

If you set the `config.srcDir.pathname`, please try one of the working path syntaxes.  If that doesn't work, please create a reproduction of the error that I can study, and I can try debugging that.  I’ll close the issue for now, but please let me know if you can still reproduce the error
