### ISSUE TITLE
When building dynamic pages, they are build twice

### ISSUE THREAD

**Issue by tiwka19** [jlarmstrongiv/astro-i18n-aut#42]
![image](https://github.com/jlarmstrongiv/astro-i18n-aut/assets/61656257/19e6a78a-e29c-49d3-82cc-7a388bcc0751)
![image](https://github.com/jlarmstrongiv/astro-i18n-aut/assets/61656257/b26f7405-59e0-4c53-a33e-bf9dc28f5d8e)

**Comment by jlarmstrongiv** [comment]
Ahh, good point, that’s needed for the `redirectDefaultLocale` for SSG, but could be removed for SSR.

**Comment by jlarmstrongiv** [comment]
@tiwka19 should be fixed in `0.6.2`

**Comment by tiwka19** [comment]
> Ahh, good point, that’s needed for the `redirectDefaultLocale` for SSG, but could be removed for SSR.

so it's required for SSG? Also notice the time build difference 🥲

**Comment by jlarmstrongiv** [comment]
@tiwka19 unfortunately, yes.  Astro middleware in SSG cannot run in routes that do not exist.  So we have to create the routes for the middleware to `redirectDefaultLocale`.  If you don’t need that redirect, disabling `redirectDefaultLocale` will disable those routes too
