### ISSUE TITLE
Is it possible to combine with the official integration for dynamic pages only?

### ISSUE THREAD

**Issue by tiwka19** [jlarmstrongiv/astro-i18n-aut#43]
I need to pass a different language for each language to getStaticPaths to filter languages. But, because it is not possible to pass a variable inside the function, can I create folders with languages inside pages (as suggested by the official integration), and add blog pages there?

**Comment by jlarmstrongiv** [comment]
Hi @tiwka19, unfortunately, the [official integration](https://docs.astro.build/en/recipes/i18n/#_top) is not compatible with [`astro-i18n-aut`](https://www.npmjs.com/package/astro-i18n-aut)
