### ISSUE TITLE
Support Astro 4.2 with new Reworked routing priority for injected routes?

### ISSUE THREAD

**Issue by somethingxdev** [jlarmstrongiv/astro-i18n-aut#45]
Hi. Astro have added a new implementation of routes. Will you be updating your plugin?

**Comment by jlarmstrongiv** [comment]
I checked out the [release notes](https://astro.build/blog/astro-420/#experimental-reworked-routing-priority-for-injected-routes), and it seems to be an experimental config setting that will eventually become the default.  Feel free to try it out.  At first glance, it doesn't seem to affect the `astro-i18n-aut` integration.
