### ISSUE TITLE
Default locale route redirection loses query params

### ISSUE THREAD

**Issue by HenglyEver** [jlarmstrongiv/astro-i18n-aut#46]
When I go to the default locale route with some query params, it will redirect to base route without locale in path which is intended behavior but it loses the query params a long the way.

**Step to reproduces**
1. Have `en` as default locale
2. Go to `baseUrl/en?foo=bar`

**Expected behavior**
Got redirected to `baseUrl?foo=bar`

**Actual behavior**
Got redirected to `baseUrl`

**Comment by jlarmstrongiv** [comment]
Ahh, I missed that.  Feel free to make the change in 

https://github.com/jlarmstrongiv/astro-i18n-aut/blob/main/src/edge-runtime/middleware.ts

Or, I can take a look and fix it when I return from traveling in two weeks

**Comment by jlarmstrongiv** [comment]
@HenglyEver thanks for your patience!  This issue should be fixed in `0.7.0`.  If not, please let me know and I’ll re-open this issue
