### ISSUE TITLE
ENOENT: no such file or directory, lstat /src/pages

### ISSUE THREAD

**Issue by tiwka19** [jlarmstrongiv/astro-i18n-aut#5]
When I try to build a project, I get this error.

**Comment by jlarmstrongiv** [comment]
Hey @tiwka19 and @lemueldls, do you have a reproducible example I can study?  It sounds similar to #4 

I’ve tried reproducing this issue on mac, windows, and linux—but it builds successfully on all platforms.

I’m closing this issue for now, but if you would please link a github repo that reproduces the issue along with your OS, I’ll re-open the issue, take a look, and fix it once and for all.
