### ISSUE TITLE
How to fetch i18n entry from `getCollection`

### ISSUE THREAD

**Issue by willin** [jlarmstrongiv/astro-i18n-aut#56]
ref from:
https://docs.astro.build/en/recipes/i18n/#use-collections-for-translated-content

```
src/pages/[lang]/blog/[...slug].astro
```

however, i do not have a `/[lang]` folder.

![QQ_1724643805292](https://github.com/user-attachments/assets/9fea68e7-1d06-4e26-8d4b-3cecd655c5f4)

so that i have no idea how to make the `getStaticPaths` work

![QQ_1724643850999](https://github.com/user-attachments/assets/4f498962-68f5-4bd5-b6b4-eab1d3fb5725)

-----

then, i tried another way:

![QQ_1724645361748](https://github.com/user-attachments/assets/3f49d9ff-7485-485c-a5c8-d08dab0c6930)

```ts
export async function getStaticPaths() {
  const blogEntries = await getCollection('posts', ({ data }) => {
    return import.meta.env.PROD ? data.draft !== true : true;
  });
  return blogEntries.map((entry) => {
    const [lang, slug] = entry.slug.split('/');
    const postslug =
      lang === defaultLocale ? `post/${slug}/` : `${lang}/post/${slug}/`;
    return {
      params: { postslug },
      props: { entry }
    };
  });
}
```

```js
[
  {
    params: { postslug: 'en/post/astro-blog-from-scratch/' },
    props: { entry: [Object] }
  },
  {
    params: { postslug: 'post/astro-blog-from-scratch/' },
    props: { entry: [Object] }
  }
]
```

however, still default locale content all the time.

**Comment by jlarmstrongiv** [comment]
Hi @willin, please check the README for:

- documentation on this library
- how to use it with content collections
- limitations regarding `getStaticPaths`

The Astro docs you linked are a completely different approach to i18n.
